USE [master]

/****** Object:  Database [ListaPresenca]    Script Date: 12/03/2016 13:45:50 ******/
CREATE DATABASE [ListaPresenca]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ListaPresenca', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ListaPresenca.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ListaPresenca_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ListaPresenca_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

ALTER DATABASE [ListaPresenca] SET COMPATIBILITY_LEVEL = 120

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ListaPresenca].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [ListaPresenca] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [ListaPresenca] SET ANSI_NULLS OFF 

ALTER DATABASE [ListaPresenca] SET ANSI_PADDING OFF 

ALTER DATABASE [ListaPresenca] SET ANSI_WARNINGS OFF 

ALTER DATABASE [ListaPresenca] SET ARITHABORT OFF 

ALTER DATABASE [ListaPresenca] SET AUTO_CLOSE OFF 

ALTER DATABASE [ListaPresenca] SET AUTO_SHRINK OFF 

ALTER DATABASE [ListaPresenca] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [ListaPresenca] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [ListaPresenca] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [ListaPresenca] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [ListaPresenca] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [ListaPresenca] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [ListaPresenca] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [ListaPresenca] SET  DISABLE_BROKER 

ALTER DATABASE [ListaPresenca] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [ListaPresenca] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [ListaPresenca] SET TRUSTWORTHY OFF 

ALTER DATABASE [ListaPresenca] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [ListaPresenca] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [ListaPresenca] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [ListaPresenca] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [ListaPresenca] SET RECOVERY SIMPLE 

ALTER DATABASE [ListaPresenca] SET  MULTI_USER 

ALTER DATABASE [ListaPresenca] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [ListaPresenca] SET DB_CHAINING OFF 

ALTER DATABASE [ListaPresenca] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [ListaPresenca] SET TARGET_RECOVERY_TIME = 0 SECONDS 

ALTER DATABASE [ListaPresenca] SET DELAYED_DURABILITY = DISABLED 
