//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurmaHora
    {
        public int SEQ_DISCIPLINA_TURMA { get; set; }
        public int DIA { get; set; }
        public int HORA { get; set; }
        public string CODIGO_ESPACO { get; set; }
    
        public virtual Datahora Datahora { get; set; }
        public virtual DisciplinaTurma DisciplinaTurma { get; set; }
    }
}
